framework:
    session:
        enabled: true
        handler_id: null
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers:
        - 'X-Forwarded-Proto'
        - 'X-Forwarded-Host'
        - 'X-Forwarded-Port'
        - 'X-Forwarded-For'

    mailer:
        dsn: '%env(MAILER_DSN)%'
