oidc_sso:
  path: /oidc/sso
  controller: App\Controller\OidcController::sso
  methods: [POST]

oidc_callback:
  path: /oidc/callback
  controller: App\Controller\OidcController::callback

mail_send:
  path: /mail/send
  controller: App\Controller\MailController::sendEmail
