services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Symfony\Component\Mailer\MailerInterface:
        alias: Symfony\Component\Mailer\Mailer